### ISSUE TITLE
mime not supported (webm)

### ISSUE THREAD

**Issue by iGormilhit** [benpro/PHPmyLMB#30]
Hello (again),

J'ai dû faire une erreur à quelque part. Quand je vais sur [une des vidéos](https://id-libre.org/media/?id=2&file=arte/Puissante_et_incontrolee_la_troika-2015_02_24_22h30.webm&sort=asc) que je voudrais mettre à disposition va PHPmyLMB, j'ai un message comme quoi "Le format Vidéo ou le type mime n'est pas supporté", pourtant mediainfo me dit bien que c'est un WebM et ce format est activé dans le ``config.local.php``.

Cette même vidéo tourne dans un lecteur html5 : https://id-libre.org/file/presse/radio/puissante-troika/

Dans le log des erreurs apache, il n'y pas de message relié.

Je tourne sous une debian wheezy, apache 2.2 et php 5.6.14-1.

**Comment by benpro** [comment]
C'est probablement un bug apache. Tu peux tester la branche dev ? Y'a une correction possible.
Si ça marche je vais le merger dans master.

**Comment by iGormilhit** [comment]
Ça fonctionne bien mieux en effet.

Je suis passé sur la branche dev. Je peux afficher les *detailed informations*, ce que je ne pouvais pas faire avant, et mes deux fichiers webm sont reconnus et jouables.

Par contre, j'en ai ajouté un troisième qui n'apparaît pas, mais c'est certainement un autre problème.

Merci pour ta réponse !

**Comment by benpro** [comment]
Ok j'ai mergé le patch sur master.
